version: '3.4'

services:
  altridserver:
    image: altrid-server
    environment:
      NODE_ENV: production
    volumes:
      - ./configs/config.json:/app/configs/config.json
      - ./UploadedFiles:/app/UploadedFiles
    ports:
      - 9000:9000
