name: Close release branch

env:
  RELEASE_BRANCH_PREFIX: "release-test/"
  TIMEZONE: "Asia/Seoul"

on:
  workflow_dispatch:

jobs:
  close-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all remote branches
        run: git fetch --prune --all

      - name: Get lastest release branch
        run: |
          LATEST_BRANCH=$(git branch -r --sort=-committerdate | grep $RELEASE_BRANCH_PREFIX | head -n 1 | sed 's/origin\///' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          echo "LATEST_RELEASE_BRANCH=$LATEST_BRANCH" >> $GITHUB_ENV

      - name: Current release branch
        run: echo "$LATEST_RELEASE_BRANCH"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install standard-version
        run: npm install standard-version

      - name: Install git-flow
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow

      - name: Finish release
        run: |
          branch=$(echo $LATEST_RELEASE_BRANCH | cut -d'/' -f2)
          git remote update
          git fetch
          git checkout develop
          git pull origin develop
          git checkout -t origin/$LATEST_RELEASE_BRANCH
          git pull origin $LATEST_RELEASE_BRANCH
          git pull origin master
          npm run standard-version -- --release-as minor
          git flow release finish -Fpn $branch
