name: 릴리즈 브랜치 닫기

env:
  TIMEZONE: "Asia/Seoul"
  GET_BRANCH_NAME_URL: "https://educore-release-list.run.goorm.app/branch-name"
  PATCH_SEQUENCE_NUMBER_URL: "https://educore-release-list.run.goorm.app/sequence"

on:
  workflow_dispatch:

jobs:
  close-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Fetch all remote branches
        run: |
          git fetch --unshallow --tags --all
          git checkout master

      - name: Get current opened release branch name
        run: |
          RESPONSE=$(curl -X GET -H 'Content-type: application/json' -H 'eduReleaseGithubActionToken: tmpToken' "$GET_BRANCH_NAME_URL")
          echo "CURRENT_RELEASE_BRANCH=$RESPONSE" >> $GITHUB_ENV

      - name: Current release branch
        run: echo "Current release branch is $CURRENT_RELEASE_BRANCH"

      - name: Checkout to release branch
        run: git checkout -t origin/$CURRENT_RELEASE_BRANCH

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config pull.rebase false

      - name: Install git-flow
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow
          git flow init -d

      - name: Finish release
        run: |
          branch=$(echo $CURRENT_RELEASE_BRANCH | cut -d'/' -f2)
          git fetch
          echo "STEP 1: 릴리즈 브랜치 최신화"
          git pull origin $CURRENT_RELEASE_BRANCH
          echo "STEP 2: Merging master to release branch..."
          git pull origin master
          echo "STEP 3: 버전 업 및 체인지 로그 생성"
          npx standard-version -- --release-as minor
          echo "STEP 4: 릴리즈 브랜치 닫기"
          git flow release finish -Fpn $branch
          echo "STEP 5: 새로운 태그 푸시"
          git push --tags

      - name: Increase release sequence number
        run: |
          RESPONSE=$(curl -X PATCH -H 'Content-type: application/json' -H 'eduReleaseGithubActionToken: tmpToken' "$PATCH_SEQUENCE_NUMBER_URL")
          echo "Today's next release sequence is $RESPONSE"
