name: Get Latest Release Branch

on:
  workflow_dispatch:

jobs:
  get_latest_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all remote branches
        run: git fetch --prune --all

      - name: Get the latest release branch
        id: get_latest_release_branch
        run: |
          # Get the latest release branch
          LATEST_BRANCH=$(git branch -r --sort=-committerdate | grep 'origin/release-test/' | head -n 1 | sed 's/origin\///')
          
          # Save the result to GitHub Actions environment variable
          echo "LATEST_RELEASE_BRANCH=$LATEST_BRANCH" >> $GITHUB_ENV

      - name: Display the latest release branch
        run: echo "The latest release branch is $LATEST_RELEASE_BRANCH"
