name: Close release branch

env:
  RELEASE_BRANCH_PREFIX: "release-test/"
  TIMEZONE: "Asia/Seoul"

on:
  workflow_dispatch:

jobs:
  close-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get lastest release branch
        run: |
          LATEST_BRANCH=$(git branch -r --sort=-committerdate | grep 'origin/release/' | head -n 1 | sed 's/origin\///')
          echo "LATEST_RELEASE_BRANCH=$LATEST_BRANCH" >> $GITHUB_ENV

      - name: Current release branch
        run: echo "$LATEST_RELEASE_BRANCH"
